logging:
  level:
    com:
      mellora: debug
    org:
      springframework: error
spring:
  main:
    banner-mode: 'off'
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mellora
    driver-class-name: org.h2.Driver