logging:
  level:
    com:
      mellora: INFO
    org:
      springframework: ERROR
    root: ERROR
spring:
  main:
    banner-mode: 'off'
  h2:
    console:
      enabled: true
  datasource:
    hikari:      connection-timeout: 20000
      maximum-pool-size: 5